In [11]:
import numpy as np
from numpy.linalg import inv

v1 = np.array([1,1,1])
v2 = np.array([1,0,0])

x = np.array([[1, 1],[1, 0],[1,0]])
xt = x.transpose()

In [29]:
xt

array([[1, 1, 1],
       [1, 0, 0]])

In [12]:
xtx = np.dot(xt, x)

In [10]:
xtx

array([[3, 1],
       [1, 1]])

In [16]:
xtx_inv = inv(xtx)

In [21]:
xtx_inv

array([[ 0.5, -0.5],
       [-0.5,  1.5]])

In [31]:
innerproduct = np.matmul(xtx_inv, xt)

In [38]:
p1 = np.array([3,3,3])
bp1 = np.dot(innerproduct, p1)
bp1

array([3.00000000e+00, 3.33066907e-16])

In [37]:
p2 = np.array([1,2,3])
bp2 = np.dot(innerproduct, p2)
bp2

array([ 2.5, -1.5])

In [42]:
p3 = np.array([0,0,1])
bp3 = np.dot(innerproduct, p3)
bp3

array([ 0.5, -0.5])

In [39]:
p1hat = np.dot(x, bp1)
p1hat

array([3., 3., 3.])

In [40]:
p2hat = np.dot(x, bp2)
p2hat

array([1. , 2.5, 2.5])

In [43]:
p3hat = np.dot(x, bp3)
p3hat

array([1.11022302e-16, 5.00000000e-01, 5.00000000e-01])